<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OUBGVRC" ignored="1" name="Test(failed)" tests="4" failures="2" timestamp="2023-01-11T18:52:15 IST" time="296.867" errors="0">
  <testcase name="verifyFinishButnTest" time="1.562" classname="TestCases.CheckoutOverviewTest">
    <failure type="java.lang.AssertionError" message="expected [.FINISH] but found [FINISH]">
      <![CDATA[java.lang.AssertionError: expected [.FINISH] but found [FINISH]
at TestCases.CheckoutOverviewTest.verifyFinishButnTest(CheckoutOverviewTest.java:80)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyFinishButnTest -->
  <testcase name="verifyDescriptionTextTest" time="1.055" classname="TestCases.CheckoutOverviewTest"/>
  <testcase name="verifyCancelButnTest" time="7.645" classname="TestCases.CheckoutOverviewTest">
    <failure type="java.lang.AssertionError" message="expected [.CANCEL] but found [CANCEL]">
      <![CDATA[java.lang.AssertionError: expected [.CANCEL] but found [CANCEL]
at TestCases.CheckoutOverviewTest.verifyCancelButnTest(CheckoutOverviewTest.java:71)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyCancelButnTest -->
  <testcase name="verifyQuntyTextTest" time="0.897" classname="TestCases.CheckoutOverviewTest"/>
  <testcase name="verifyCheckoutOverviewTextTest" time="0.0" classname="TestCases.CheckoutOverviewTest">
    <ignored/>
  </testcase> <!-- verifyCheckoutOverviewTextTest -->
</testsuite> <!-- Test(failed) -->
